### ISSUE TITLE
Add support for specific tsconfig file path inside of vue-jest jest.config.js options

### ISSUE THREAD

**Issue by JessicaSachs** [vuejs/vue-jest#309] opened 2020-12-07 17:43 UTC
We refactored vue-jest to have better tsconfig support by recursively walking up the directory structure, but sometimes users use sibling directories to store their build + config settings.

Can we specify a tsconfig path inside of jest.config.js? Perhaps relative to `<rootDir>`?

**Comment by xiaohulu** [comment] 2021-03-08 06:55
My project is a electron app, I put  `tsconfig.json` at `src/renderer/`, when I run `npm run jest` report below errors:

```
 FAIL  src/renderer/layout/titlebar/__test__/Titlebar.spec.ts
  ● Test suite failed to run

    TypeError: Cannot read property 'compilerOptions' of null

      at Object.transpileModule (../../node_modules/typescript/lib/typescript.js:131656:40)
      at Object.process (../../node_modules/vue-jest/lib/transformers/typescript.js:22:28)
      at processScript (../../node_modules/vue-jest/lib/process.js:44:30)
      at Object.module.exports [as process] (../../node_modules/vue-jest/lib/process.js:140:24)
      at ScriptTransformer.transformSource (../../node_modules/@jest/transform/build/ScriptTransformer.js:464:35)
      at ScriptTransformer._transformAndBuildScript (../../node_modules/@jest/transform/build/ScriptTransformer.js:569:40)
      at ScriptTransformer.transform (../../node_modules/@jest/transform/build/ScriptTransformer.js:613:25)
```
I found `resolveTsConfigSync` just resolve tsconfig at root dir, see https://github.com/vuejs/vue-jest/pull/307#r589193388

vue-jest `5.0.0-alpha.7`

**Comment by lmiller1990** [comment] 2021-03-08 12:02
@xiaohulu we should definitely support this. Are you interested in making a PR? I made a suggestion on how to do this [here](https://github.com/vuejs/vue-jest/pull/307#discussion_r589370897).

**Comment by xiaohulu** [comment] 2021-03-08 22:40
@lmiller1990  I'll try to make a PR, but I'm not sure if I can do it well。

**Comment by lmiller1990** [comment] 2021-03-09 01:05
Give it a try :) if you get stuck ask - I can help out.

**Comment by xiaohulu** [comment] 2021-03-10 11:25
@lmiller1990 Throw errors when I run `yarn test:e2e` on win10

```
[vue-jest]: (babel-in-package) Copying vue-jest into node_modules

'cp' is not an internal or external command, nor is it a runnable program  or batch file
error Command failed with exit code 1.
```

**Comment by xiaohulu** [comment] 2021-03-10 13:36
@lmiller1990 I make a PR.

Another question about typescript. I try to change `package.json` to below code which use `ts-jest`. Run `yarn test:e2e` then report errors

```json
{
  "name": "typescript",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "private": true,
  "scripts": {
    "test": "jest --no-cache ./sub-project/test.js"
  },
  "dependencies": {
    "vue": "3.0.0-alpha.10"
  },
  "devDependencies": {
    "@types/jest": "^26.0.20",
    "ts-jest": "^26.5.3",
    "typescript": "^4.2.3",
    "jest": "^24.0.0"
  },
  "jest": {
    "globals": {
      "vue-jest": {
        "tsConfig": "./sub-project/tsconfig.json"
      }
    },
    "moduleFileExtensions": [
      "js",
      "ts",
      "json",
      "vue"
    ],
    "transform": {
      "^.+\\.js$": "ts-jest",
      "^.+\\.vue$": "../../../lib/index.js"
    }
  }
}
```
then report errors. Did I miss something?

```sh
{
  "name": "typescript",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "private": true,
  "scripts": {
    "test": "jest --no-cache ./sub-project/test.js"
  },
  "dependencies": {
    "vue": "3.0.0-alpha.10"
  },
  "devDependencies": {
    "@types/jest": "^26.0.20",
    "ts-jest": "^26.5.3",
    "typescript": "^4.2.3",
    "jest": "^24.0.0"
  },
  "jest": {
    "globals": {
      "vue-jest": {
        "tsConfig": "./sub-project/tsconfig.json"
      }
    },
    "moduleFileExtensions": [
      "js",
      "json",
      "vue"
    ],
    "transform": {
      "^.+\\.js$": "ts-jest",
      "^.+\\.vue$": "../../../lib/index.js"
    }
  }
}
```

**Comment by lmiller1990** [comment] 2021-03-15 07:27
Hi! 

Regarding `cp` ... yep, it's only going to work on a linux env. The problem is [here](https://github.com/vuejs/vue-jest/blob/71e87c1cea5f73df5493628ac163f4c37c5190b0/e2e/test-runner.js#L60.

You could rewrite that part of the code using `fs` perhaps, so it's cross platform.

Regarding the second error - you might need to install `babel-jest`. Jest will not read ES modules out of the box. Just installing `babel-jest` (should) let it work.

If not, please push your branch and write instructions so I can try running it. This project is pretty tricky and annoying to work on at times, but I'm sure we can get this to work 👍

**Comment by nogic1008** [comment] 2021-03-29 05:04
PR contains linguish error, so I fixed & merged.
@lmiller1990 I'll fix test-script issue on Windows soon.

**Closed by nogic1008** 2021-03-29 05:04 UTC
Labels: 5.x, intend to implement

**Comment by lmiller1990** [comment] 2021-03-30 07:59
Thanks.

You are now added a collab. Feel free to make fixes/close issues if you want, let me know if you need any help with anything.
