### ISSUE TITLE
$refs doesn't work when using v-for and destructuring

### ISSUE THREAD

**Issue by adrianosmond** [vuejs/vue-jest#306] opened 2020-11-16 12:33 UTC
### Version
1.1.1

### Reproduction link
[https://github.com/adrianosmond/refs-v-for-and-rest-destructuring](https://github.com/adrianosmond/refs-v-for-and-rest-destructuring)

### Steps to reproduce
The repo above is set up so that running the tests (with `npm run test`) will fail on the component (src/components/Broken.vue) which combines object rest destructuring, ref="" and v-for like so:
```
<li v-for="{key, label, ...toBind} in items" :key="key" ref="listItem">
    <a v-bind="toBind">{{ label }}</a>
</li>
```

This works fine in Vue itself, as can be seen if you run the project (`npm run serve`) and open it in your browser on port 8080.

A component (src/components/Working.vue) is also included which is identical except that it doesn't use rest destructuring inside v-for. The same test then passes for this component.

### What is expected?
`$refs.listItem` should be an array containing 2 `<li>` elements

### What is actually happening?
`$refs.listItem` is undefined

**Comment by lmiller1990** [comment] 2020-12-06 12:52
Vue Jest does not like the rest operator (`...`) in `<template>`.

**Comment by renatodeleao** [comment] 2022-02-22 17:06
Heya there! 👋   

Was about to report the same problem. My whole component test suite got red because I just `destructured` the loop item. With this change, logging `wrapper.html()` returns a blank string which is probably why my test's `wrapper.find()` fail to find anything. Did you ever got a lead on what's the cause @lmiller1990? Does this still happen at v2? 

```diff
 <v-menu v-bind="menu.props">
-    <template v-for="(item, i) in menu.items"> <!-- works -->
+    <template v-for="({ component, ...item }, i) in menu.items"> <!-- breaks -->
      <component
-       :is="item.component"
+       :is="component"
        :key="item.id"
        v-test="{ id: 'menu-item' }"
        v-bind="item"
      >
        {{ item.label }}
      </component>
    </template>
  </v-menu>
```

Cheers ✌️

**Comment by lmiller1990** [comment] 2022-02-22 23:54
This is nothing to do with Test Utils - I'm guessing the problem is that when we turn the `<template>` into JS for Jest to read, we do **not** do any parsing of `...` (or for that matter, anything in `<template>`. As noted [here](https://github.com/vuejs/vue-jest/issues/306#issuecomment-739498591) this problem doesn't happen with webpack-mocha.

Can you confirm what version of vue-jest you are using? See [here](https://github.com/vuejs/vue-jest#installation) for the versions. This issue is quite old - I wonder if it's fixed using Jest 27 and the latest `@vue/vue2-jest`.

**Comment by renatodeleao** [comment] 2022-02-23 09:54
@lmiller1990 many thanks for the explanation! You can stop wondering: it works with `jest@27` and latest `@vue/vue2-jest`. I'm sry for not checking basic setup instructions and consequently reviving this thread. Cheers!

```diff
// setup
{
  "vue": "2.6.14",
-  "vue-jest": "3.0.7",
+  "@vue/vue2-jest": "27.0.0-alpha.4",
  "jest": "27.5.1",
  "babel-jest": "27.5.1"
}
```

**Comment by lmiller1990** [comment] 2022-02-24 01:07
Nice, seems I won't need to spend much more time on this. 3.0.7 is a really old build, glad you got it working. New Vue CLI templates ship the latest vue2-jest, so should be good moving forward.

Going to close this one off as solved/wontfix.

**Closed by lmiller1990** 2022-02-24 01:07 UTC
